import type { Point } from './types';
import type { BloodSplash } from './bloodSplash';
import type { Mosquito } from './mosquito';
export function drawBackground(ctx: CanvasRenderingContext2D, w: number, h: number){ ctx.fillStyle = '#ffffff'; ctx.fillRect(0,0,w,h); }
export function drawTrail(ctx: CanvasRenderingContext2D, points: Point[]){ if (!points.length) return; ctx.strokeStyle='rgba(120,120,120,0.7)'; ctx.lineWidth=2; ctx.beginPath(); ctx.moveTo(points[0].x, points[0].y); for (let i=1;i<points.length;i++) ctx.lineTo(points[i].x, points[i].y); ctx.stroke(); }
export function drawMosquito(ctx: CanvasRenderingContext2D, x: number, y: number){ const wingOffset=Math.sin(performance.now()*0.02)*10; ctx.fillStyle='#000'; ctx.beginPath(); ctx.ellipse(x,y,10,5,0,0,Math.PI*2); ctx.fill(); ctx.beginPath(); ctx.arc(x+12,y,6,0,Math.PI*2); ctx.fill(); ctx.fillStyle='rgba(150,150,150,0.8)'; ctx.beginPath(); ctx.ellipse(x-5,y-15+wingOffset,9,4,0,0,Math.PI*2); ctx.fill(); ctx.beginPath(); ctx.ellipse(x-5,y+7-wingOffset,9,4,0,0,Math.PI*2); ctx.fill(); ctx.strokeStyle='#000'; ctx.lineWidth=2; for (let i=-1;i<=1;i++){ ctx.beginPath(); ctx.moveTo(x-5,y+5); ctx.lineTo(x-15,y+10+i*5); ctx.stroke(); } ctx.beginPath(); ctx.moveTo(x+18,y); ctx.lineTo(x+28,y); ctx.stroke(); }
export function drawKillMarker(ctx: CanvasRenderingContext2D, x: number, y: number){ ctx.strokeStyle='rgba(220,30,30,0.9)'; ctx.lineWidth=3; ctx.beginPath(); ctx.arc(x+12,y,10,0,Math.PI*2); ctx.stroke(); ctx.beginPath(); ctx.moveTo(x+6,y-6); ctx.lineTo(x+18,y+6); ctx.stroke(); ctx.beginPath(); ctx.moveTo(x+18,y-6); ctx.lineTo(x+6,y+6); ctx.stroke(); }
export function drawBloodSplash(ctx: CanvasRenderingContext2D, s: BloodSplash){ if (!s.alive) return; ctx.fillStyle='rgb(220,30,30)'; ctx.beginPath(); ctx.arc(s.x,s.y,8,0,Math.PI*2); ctx.fill(); ctx.fillStyle='rgb(160,10,10)'; ctx.beginPath(); ctx.arc(s.x,s.y,4,0,Math.PI*2); ctx.fill(); for (const d of s.drops){ ctx.fillStyle='rgb(220,30,30)'; ctx.beginPath(); ctx.arc(s.x+d.dx, s.y+d.dy, d.r, 0, Math.PI*2); ctx.fill(); ctx.fillStyle='rgb(160,10,10)'; ctx.beginPath(); ctx.arc(s.x+d.dx, s.y+d.dy, Math.max(1,d.r/2),0,Math.PI*2); ctx.fill(); } }
export function drawRacket(ctx: CanvasRenderingContext2D, x: number, y: number){ const headRadius=26; ctx.strokeStyle='#000'; ctx.lineWidth=3; ctx.beginPath(); ctx.arc(x,y,headRadius,0,Math.PI*2); ctx.stroke(); ctx.save(); ctx.beginPath(); ctx.arc(x,y,headRadius-2,0,Math.PI*2); ctx.clip(); ctx.strokeStyle='rgb(210,210,210)'; ctx.lineWidth=1; const step=6; for(let dx=-headRadius+3; dx<headRadius; dx+=step){ const xx=x+dx; ctx.beginPath(); ctx.moveTo(xx,y-headRadius); ctx.lineTo(xx,y+headRadius); ctx.stroke(); } for(let dy=-headRadius+3; dy<headRadius; dy+=step){ const yy=y+dy; ctx.beginPath(); ctx.moveTo(x-headRadius,yy); ctx.lineTo(x+headRadius,yy); ctx.stroke(); } ctx.restore(); ctx.lineWidth=8; ctx.strokeStyle='#000'; ctx.beginPath(); ctx.moveTo(x+headRadius-4,y+headRadius-4); ctx.lineTo(x+headRadius+50,y+headRadius+70); ctx.stroke(); ctx.lineWidth=3; ctx.strokeStyle='rgb(180,180,180)'; ctx.beginPath(); ctx.moveTo(x+headRadius-4,y+headRadius-4); ctx.lineTo(x+headRadius+50,y+headRadius+70); ctx.stroke(); }
export function drawMosquitoEntity(ctx: CanvasRenderingContext2D, m: Mosquito){ const { x, y } = m.currentPos(); if (m.dead) drawKillMarker(ctx,x,y); else drawMosquito(ctx,x,y); }